#!/usr/bin/env bash
# Adds a custom header to the response of the server 54.85.138.35
# This script configures a brand new Ubuntu machine to contain custom header

sudo apt-get update -y
sudo apt-get install -y nginx
header="\\\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "26i $header" /etc/nginx/nginx.conf
sudo service nginx restart
