#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine to contain custom header

sudo apt-get update -y
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.orig}

printf %s "
listen main
    bind *:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor  
    server 272285-web-01 52.3.251.52 check
    server 272285-web-02 54.85.138.35 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start

