#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine to contain custom header

sudo apt-get update -y
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

 
frontend muoki_frontend
    bind *:80
    default_backend my_backend

backend muoki_backend
    balance roundrobin
    server 272285-web-01 52.3.251.52:80
    server 272285-web-01 54.85.138.35:80

" >> /etc/haproxy/haproxy.cfg

service haproxy start

