#!/usr/bin/env bash
# When passing the argument start:
#	Starts manage_my_process
#	Creates a file containing its PID in /var/run/my_process.pid
#	Displays manage_my_process started
# When passing the argument stop:
#	Stops manage_my_process
#	Deletes the file /var/run/my_process.pid
#	Displays manage_my_process stopped
# When passing the argument restart
#	Stops manage_my_process
#	Deletes the file /var/run/my_process.pid
#	Starts manage_my_process
#	Creates a file containing its PID in /var/run/my_process.pid
#	Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed

if [ -z "$1" ]
then
	echo "Usage: manage_my_process {start|stop|restart}"
fi

if [ "$1" = "start" ]
then
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"
fi

if [ "$1" = "stop" ]
then
	sudo rm -rf /var/run/my_process.pid
	echo "manage_my_process stopped"
	pkill -f ./manage_my_process
fi

if [ "$1" = "restart" ]
then
	pkill -f ./manage_my_process
	sudo rm /var/run/my_process.pid
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process restarted"
fi
