#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinately
# and prints "I am invincible" if process receives a SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible"' SIGTERM 
done
