#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinately
# and prints "I am invincible" if process receives a SIGTERM

while ((1))
do
	trap 'echo "I am invincible"' SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
