#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinately
# and prints "I am invincible" if process receives a SIGTERM

while ((1))
do
	if ((SIGTERM))
		then
		echo "I am invincible"
	fi

	echo "To infinity and beyond"
	sleep 2
done
