#!/usr/bin/env bash
# Displays numbers 1 to 100 and replaces number with: Fizz if
# divisible by 3, Buzz if divisibe by 5 and FIZZBUZZ if
# divisible by both

i=1
for ((i = 1; i <= 100; i++))
do
	if ((i % 3 == 0 && i % 5 == 0))
	then
		echo "FizzBuzz"

	elif ((i % 3 == 0))
	then
		echo "Fizz"

	elif ((i % 5 == 0))
	then
		echo "Buzz"
	
	else
		echo "$i"
	fi
done
